version: '3.8'

networks:
  devops:
    external: true

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
      - devops
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
