version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
